#!/usr/bin/env bash
#
#  bitxd The bitx core server.
#
#
# chkconfig: 345 80 20
# description: bitxd
# processname: bitxd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/bitxd, see below
if [ -f /etc/sysconfig/bitxd ]; then
        . /etc/sysconfig/bitxd
fi

RETVAL=0

prog=bitxd
# you can override the lockfile via BITXD_LOCKFILE in /etc/sysconfig/bitxd
lockfile=${BITXD_LOCKFILE-/var/lock/subsys/bitxd}

# bitxd defaults to /usr/bin/bitxd, override with BITXD_BIN
bitxd=${BITXD_BIN-/usr/bin/bitxd}

# bitxd opts default to -disablewallet, override with BITXD_OPTS
bitxd_opts=${BITXD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $bitxd $bitxd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
