description "BitX Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env BITXD_BIN="/usr/bin/bitxd"
env BITXD_USER="bitx"
env BITXD_GROUP="bitx"
env BITXD_PIDDIR="/var/run/bitxd"
# upstart can't handle variables constructed with other variables
env BITXD_PIDFILE="/var/run/bitxd/bitxd.pid"
env BITXD_CONFIGFILE="/etc/bitx/bitx.conf"
env BITXD_DATADIR="/var/lib/bitxd"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # bitxd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$BITXD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run bitxd."
        echo "The setting must appear in $BITXD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"BitX Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$BITXD_PIDDIR"
    chmod 0755 "$BITXD_PIDDIR"
    chown $BITXD_USER:$BITXD_GROUP "$BITXD_PIDDIR"
    chown $BITXD_USER:$BITXD_GROUP "$BITXD_CONFIGFILE"
    chmod 0660 "$BITXD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$BITXD_PIDFILE" \
    --chuid $BITXD_USER:$BITXD_GROUP \
    --exec "$BITXD_BIN" \
    -- \
    -pid="$BITXD_PIDFILE" \
    -conf="$BITXD_CONFIGFILE" \
    -datadir="$BITXD_DATADIR" \
    -disablewallet \
    -daemon

